[tool.vibelint]
include_globs = [
    "**/*",
]

exclude_globs = [
    ".git/*",
    ".vscode-server/*",
    ".dotnet/*",
    ".cache/*",
    "**/build/**",
    "**/logs/**",
    ".vscode/*",
    "**/node_modules/**",
    "**/package-lock.json",
    "changes.md",
]